/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Business;
import model.Course;
import model.CourseEnrolled;
import model.ProfessorProfile;

/**
 *
 * @author saralask
 */
public class GraduationAuditJPanel extends javax.swing.JPanel {

    
    JPanel CardSequencePanel;
    Business business;
    String studentID;
    /**
     * Creates new form GraduationAuditJPanel
     */
    public GraduationAuditJPanel(Business bz, JPanel jp, String studentID) {
        initComponents();
        CardSequencePanel = jp;
        this.business = bz;
        this.studentID = studentID;
        btnGraduate.setVisible(false);
        setVisibility(false);
        populateTable();
    }
    
     private void populateTable(){
        
        ArrayList<CourseEnrolled> coursesEnrolled = business.getStudentDirectory().findStudent(String.valueOf(studentID)).getCourseWork().getCourseEnrolledList();
        
        DefaultTableModel model = (DefaultTableModel) tblCourse.getModel();
        model.setRowCount(0);
        
        int grades=0;
        if(coursesEnrolled!=null){
            for(CourseEnrolled course : coursesEnrolled){
                
            String professorID = course.getCourse().getProfessorId();
            ProfessorProfile professor = business.getProfessorDirectory().findProfessor(professorID);
            
            Object[] row = new Object[5];
            row[0] = course;
            row[1] = course.getCourse().getCourseName();
            row[2] = course.getCourse().getCourseInstructor();
            row[3] = course.getGradeEarned();
            int repIndex = (professor.getReputativeIndex() == 0) ? 0 : professor.getReputativeIndex(); 
            row[4] = repIndex;
            model.addRow(row);
            grades+=course.getCourse().getCreditsCarried();
        } 
        }
        
        business.getStudentDirectory().findStudent(studentID).setTotalGradesEarned(grades);
        txtGrades.setText(String.valueOf(grades));
        if(grades<8){
            lblEvaluation.setText("You are lagging "+(8-grades)+" grades to graduate");
        }else{
            btnGraduate.setVisible(true);
        }
        
    }
     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourse = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtGrades = new javax.swing.JTextField();
        lblEvaluation = new javax.swing.JLabel();
        btnGraduate = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        btnRateYourProfessor = new javax.swing.JButton();
        lblCourseInstructor = new javax.swing.JLabel();
        lblCourseName = new javax.swing.JLabel();
        lblCourseID = new javax.swing.JLabel();
        lblHeading = new javax.swing.JLabel();
        txtCourseInstructor = new javax.swing.JTextField();
        txtCourseName = new javax.swing.JTextField();
        txtCourseID = new javax.swing.JTextField();
        lblRate = new javax.swing.JLabel();
        comboBoxRate = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(203, 231, 229));

        tblCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Name", "Instructor ", "Grade Earned", "Reputative Index"
            }
        ));
        tblCourse.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblCourseFocusGained(evt);
            }
        });
        tblCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCourseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCourse);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel1.setText("Total Grades Earned");

        btnGraduate.setBackground(new java.awt.Color(23, 65, 68));
        btnGraduate.setForeground(new java.awt.Color(255, 255, 255));
        btnGraduate.setText("GRADUATE");
        btnGraduate.setOpaque(true);
        btnGraduate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraduateActionPerformed(evt);
            }
        });

        Back.setBackground(new java.awt.Color(23, 65, 68));
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        btnRateYourProfessor.setBackground(new java.awt.Color(23, 65, 68));
        btnRateYourProfessor.setForeground(new java.awt.Color(255, 255, 255));
        btnRateYourProfessor.setText("RATE YOUR PROFESSOR");
        btnRateYourProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRateYourProfessorActionPerformed(evt);
            }
        });

        lblCourseInstructor.setText("COURSE INSTRUCTOR:");

        lblCourseName.setText("COURSE NAME:");

        lblCourseID.setText("COURSE ID:");

        lblHeading.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblHeading.setText("PLEASE RATE YOUR PROFESSOR");

        txtCourseInstructor.setEditable(false);
        txtCourseInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseInstructorActionPerformed(evt);
            }
        });

        txtCourseName.setEditable(false);
        txtCourseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseNameActionPerformed(evt);
            }
        });

        txtCourseID.setEditable(false);

        lblRate.setText("RATE OUT OF 10:");

        comboBoxRate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        btnSave.setBackground(new java.awt.Color(23, 65, 68));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Back))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 974, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblEvaluation, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(32, 32, 32)
                                    .addComponent(txtGrades, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnGraduate, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRateYourProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCourseInstructor)
                                    .addComponent(lblCourseName)
                                    .addComponent(lblCourseID)
                                    .addComponent(lblRate))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCourseInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBoxRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSave)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(lblHeading)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRateYourProfessor))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtGrades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGraduate))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEvaluation, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lblHeading)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseID)
                    .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseName)
                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseInstructor)
                    .addComponent(txtCourseInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRate)
                    .addComponent(comboBoxRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(Back)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblCourseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblCourseFocusGained

    }//GEN-LAST:event_tblCourseFocusGained

    private void tblCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCourseMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCourseMouseClicked

    private void btnGraduateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraduateActionPerformed
        JOptionPane.showMessageDialog(this, "Congragulations, You are now Graduated. You can download your transcript");
    }//GEN-LAST:event_btnGraduateActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_BackActionPerformed

    private void txtCourseInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseInstructorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseInstructorActionPerformed

    private void txtCourseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseNameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
        int selectedRowIndex = tblCourse.getSelectedRow();
        
        if(selectedRowIndex >=0){
        CourseEnrolled courseEnrolled = (CourseEnrolled) tblCourse.getValueAt(selectedRowIndex, 0);    
        String professorID = courseEnrolled.getCourse().getProfessorId();
        
        ProfessorProfile professor = business.getProfessorDirectory().findProfessor(professorID);
        int repIndex = (professor.getReputativeIndex() == 0) ? 0 : professor.getReputativeIndex();
        int newRepIndex = Integer.parseInt(comboBoxRate.getSelectedItem().toString());
        int result = (repIndex+newRepIndex)/2;
        professor.setReputativeIndex(result);
        JOptionPane.showMessageDialog(this, "Thanks for your feedback!");
        populateTable();
        setVisibility(false);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnRateYourProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRateYourProfessorActionPerformed
        
        
        int selectedRowIndex = tblCourse.getSelectedRow();
        
        if(selectedRowIndex >=0){
        setVisibility(true);    
        CourseEnrolled courseEnrolled = (CourseEnrolled) tblCourse.getValueAt(selectedRowIndex, 0);
        txtCourseID.setText(courseEnrolled.getCourse().getCourseId());
        txtCourseName.setText(courseEnrolled.getCourse().getCourseName());
        txtCourseInstructor.setText(courseEnrolled.getCourse().getCourseInstructor());
         
        }
        else{
            JOptionPane.showMessageDialog(this, "Please select a row a view");
            return;
        }
    }//GEN-LAST:event_btnRateYourProfessorActionPerformed

    private void setVisibility(boolean flag){
        lblHeading.setVisible(flag);
        lblCourseID.setVisible(flag);
        txtCourseID.setVisible(flag);
        lblCourseName.setVisible(flag);
        txtCourseName.setVisible(flag);
        lblCourseInstructor.setVisible(flag);
        txtCourseInstructor.setVisible(flag);
        lblRate.setVisible(flag);
        comboBoxRate.setVisible(flag);
        btnSave.setVisible(flag);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton btnGraduate;
    private javax.swing.JButton btnRateYourProfessor;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboBoxRate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCourseID;
    private javax.swing.JLabel lblCourseInstructor;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblEvaluation;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblRate;
    private javax.swing.JTable tblCourse;
    private javax.swing.JTextField txtCourseID;
    private javax.swing.JTextField txtCourseInstructor;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtGrades;
    // End of variables declaration//GEN-END:variables
}
