/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Activity;
import model.Business;
import model.Course;
import model.CourseDirectory;
import model.Person;
import model.UserActivity;

/**
 *
 * @author saralask
 */
public class ManageCourseByProfessorJPanel extends javax.swing.JPanel {

    JPanel CardSequencePanel;
    Business business;
    String professorID;
    static Course courseObj;
    /**
     * Creates new form ManageCourseByProfessor
     */
     public ManageCourseByProfessorJPanel(Business bz, JPanel jp, String professorID) {
        CardSequencePanel = jp;
        this.business = bz;
        this.professorID = professorID;
        initComponents();
        setVisibility(false);
        populateTable();
        
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourse = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnAssign = new javax.swing.JButton();
        lblHeading = new javax.swing.JLabel();
        lblDayOfTheWeek = new javax.swing.JLabel();
        comboBoxDayOfTheWeek = new javax.swing.JComboBox<>();
        lblTimings = new javax.swing.JLabel();
        lblFrom = new javax.swing.JLabel();
        comboBoxFromTiming = new javax.swing.JComboBox<>();
        lblTo = new javax.swing.JLabel();
        comboBoxToTiming = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        setBackground(new java.awt.Color(203, 231, 229));

        tblCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Name", "Instructor ", "Course Timings", "No of Students Registered"
            }
        ));
        tblCourse.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblCourseFocusGained(evt);
            }
        });
        tblCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCourseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCourse);

        btnSearch.setBackground(new java.awt.Color(23, 65, 68));
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnAssign.setBackground(new java.awt.Color(23, 65, 68));
        btnAssign.setForeground(new java.awt.Color(255, 255, 255));
        btnAssign.setText("ASSIGN TO ME");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        lblHeading.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblHeading.setText("Please Enter the Course Timings");

        lblDayOfTheWeek.setText("DAY OF THE WEEK:");

        comboBoxDayOfTheWeek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY" }));

        lblTimings.setText("TIMINGS:");

        lblFrom.setText("From");

        comboBoxFromTiming.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "8.00 AM", "8:30 AM", "9:00 AM", "9:30 AM", "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM", "12:00 PM", "12:30 PM", "1:00 PM", "1:30 PM", "2:00 PM", "2:30 PM", "3:00 PM", "3:30 PM", "4:00 PM", "4:30 PM", "5:00 PM", "5:30 PM", "6:00 PM", "6:30 PM", "7:00 PM", "7:30 PM", "8:00 PM", "8:30 PM", "9:00 PM", "9:30 PM", "10:00 PM" }));

        lblTo.setText("To");

        comboBoxToTiming.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "8.00 AM", "8:30 AM", "9:00 AM", "9:30 AM", "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM", "12:00 PM", "12:30 PM", "1:00 PM", "1:30 PM", "2:00 PM", "2:30 PM", "3:00 PM", "3:30 PM", "4:00 PM", "4:30 PM", "5:00 PM", "5:30 PM", "6:00 PM", "6:30 PM", "7:00 PM", "7:30 PM", "8:00 PM", "8:30 PM", "9:00 PM", "9:30 PM", "10:00 PM" }));

        btnSave.setBackground(new java.awt.Color(23, 65, 68));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        Back.setBackground(new java.awt.Color(23, 65, 68));
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch)
                        .addGap(510, 549, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(lblHeading))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTimings)
                                    .addComponent(lblDayOfTheWeek))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSave)
                                    .addComponent(comboBoxDayOfTheWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblFrom)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboBoxFromTiming, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(lblTo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboBoxToTiming, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAssign)
                .addGap(44, 44, 44)
                .addComponent(lblHeading)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDayOfTheWeek)
                    .addComponent(comboBoxDayOfTheWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimings)
                    .addComponent(lblFrom)
                    .addComponent(comboBoxFromTiming, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTo)
                    .addComponent(comboBoxToTiming, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(Back)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        Course result = business.getCourseDirectory().searchCourse(txtSearch.getText());
        if(result == null){
            JOptionPane.showMessageDialog(this, "Course number you entered does not exist", "Information", JOptionPane.INFORMATION_MESSAGE);
        }else{

            DefaultTableModel model = (DefaultTableModel) tblCourse.getModel();
            model.setRowCount(0);

            Object[] row = new Object[5];
            row[0] = result;
            row[1] = result.getCourseName();
            row[2] = result.getCourseInstructor();
            row[3] = result.getCourseTimings();
            if(result.getStudentsEnrolled()==null) row[4] = 0;
            else row[4] = result.getStudentsEnrolled().size();
            model.addRow(row);
        }

    }//GEN-LAST:event_btnSearchActionPerformed
     
    private void populateTable() {
        
        CourseDirectory courseDirectory = business.getCourseDirectory();
        DefaultTableModel model = (DefaultTableModel) tblCourse.getModel();
        model.setRowCount(0);
        
        if(courseDirectory!=null){
            for(Course course : courseDirectory.getCourseList()){
            Object[] row = new Object[5];
            row[0] = course;
            row[1] = course.getCourseName();
            row[2] = course.getCourseInstructor();
            row[3] = course.getCourseTimings() == null ? "" : course.getCourseTimings();
            if(course.getStudentsEnrolled()==null) row[4] = 0;
            else row[4] = course.getStudentsEnrolled().size();
            model.addRow(row);
        } 
        }
               
    }
    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
         
        int selectedRowIndex = tblCourse.getSelectedRow();
        
        if(selectedRowIndex >=0){
    
        Course course = (Course) tblCourse.getValueAt(selectedRowIndex, 0);
        courseObj = course;

        System.out.println(course.getCourseInstructor());
        if(course.getCourseInstructor()!=null){
            JOptionPane.showMessageDialog(this, "OOPS!, this Course has Already been assigned!");
        }
        else{course.setProfessorId(professorID);
        Person person = business.getProfessorDirectory().findProfessor(professorID).getPerson();
        course.setCourseInstructor(person.getFirstName()+" "+person.getLastName());
        JOptionPane.showMessageDialog(this, "This Course has been Assigned to you, Please provide the course timings");
        UserActivity userActitvity = new UserActivity(person.getFirstName(), "ONLINE", Activity.COURSE_INSTRUCTOR_ASSIGNED, new Date());
        business.getUserActivityDirectory().addUserActivity(userActitvity);
        setVisibility(true);
        }
        
        }

        populateTable();
        
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        String day = comboBoxDayOfTheWeek.getSelectedItem().toString();
        String fromTiming = comboBoxFromTiming.getSelectedItem().toString();
        String toTiming = comboBoxToTiming.getSelectedItem().toString();
        
        courseObj.setDayOfTheWeek(day);
        courseObj.setFromTiming(fromTiming);
        courseObj.setToTiming(toTiming);
        JOptionPane.showMessageDialog(this, "Course timings have been added");
        populateTable();
        setVisibility(false);
   
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tblCourseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblCourseFocusGained
     
    }//GEN-LAST:event_tblCourseFocusGained

    private void tblCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCourseMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCourseMouseClicked

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_BackActionPerformed


    private void setVisibility(boolean flag){
        lblHeading.setVisible(flag);
        lblDayOfTheWeek.setVisible(flag);
        comboBoxDayOfTheWeek.setVisible(flag);
        lblTimings.setVisible(flag);
        lblFrom.setVisible(flag);
        comboBoxFromTiming.setVisible(flag);
        lblTo.setVisible(flag);
        comboBoxToTiming.setVisible(flag);
        btnSave.setVisible(flag);  
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> comboBoxDayOfTheWeek;
    private javax.swing.JComboBox<String> comboBoxFromTiming;
    private javax.swing.JComboBox<String> comboBoxToTiming;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDayOfTheWeek;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblTimings;
    private javax.swing.JLabel lblTo;
    private javax.swing.JTable tblCourse;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
