/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Activity;
import model.Business;
import model.Course;
import model.CourseDirectory;
import model.CourseEnrolled;
import model.CourseWork;
import model.ProfessorProfile;
import model.StudentProfile;
import model.UserActivity;

/**
 *
 * @author saralask
 */
public class StudentCourseRegistrationJPanel extends javax.swing.JPanel {

    JPanel CardSequencePanel;
    Business business;
    String studentID;
    /**
     * Creates new form StudentCourseRegistrationJPanel
     */
    public StudentCourseRegistrationJPanel(Business bz, JPanel jp, String studentID) {
        initComponents();
        CardSequencePanel = jp;
        this.business = bz;
        this.studentID = studentID;
        setVisibility(false);
        populateTable();
    }
    
    private void setVisibility(boolean flag){
        lblHeading.setVisible(flag);
        lblCourseID.setVisible(flag);
        txtCourseID.setVisible(flag);
        lblCourseName.setVisible(flag);
        txtCourseName.setVisible(flag);
        lblCourseInstructor.setVisible(flag);
        txtCourseInstructor.setVisible(flag);
        lblCourseTimings.setVisible(flag);
        txtCourseTimings.setVisible(flag);
        lblCredits.setVisible(flag);
        txtCredits.setVisible(flag);
        lblReputativeIndex.setVisible(flag);
        txtReputativeIndex.setVisible(flag);
        btnEnroll.setVisible(flag);
    }

     private void populateTable() {
        
        CourseDirectory courseDirectory = business.getCourseDirectory();
        DefaultTableModel model = (DefaultTableModel) tblCourse.getModel();
        model.setRowCount(0);
        
        if(courseDirectory!=null){
            for(Course course : courseDirectory.getCourseList()){
            Object[] row = new Object[4];
            row[0] = course;
            row[1] = course.getCourseName();
            row[2] = course.getCourseInstructor();
            row[3] = course.getCourseTimings();
            model.addRow(row);
        } 
        }
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourse = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnEnroll = new javax.swing.JButton();
        lblCourseID = new javax.swing.JLabel();
        lblCourseName = new javax.swing.JLabel();
        lblCourseInstructor = new javax.swing.JLabel();
        lblCourseTimings = new javax.swing.JLabel();
        txtCourseID = new javax.swing.JTextField();
        txtCourseName = new javax.swing.JTextField();
        txtCourseInstructor = new javax.swing.JTextField();
        txtCourseTimings = new javax.swing.JTextField();
        lblReputativeIndex = new javax.swing.JLabel();
        txtReputativeIndex = new javax.swing.JTextField();
        btnView = new javax.swing.JButton();
        lblHeading = new javax.swing.JLabel();
        lblCredits = new javax.swing.JLabel();
        txtCredits = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(203, 231, 229));

        tblCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Name", "Instructor ", "Course Timings"
            }
        ));
        tblCourse.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblCourseFocusGained(evt);
            }
        });
        tblCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCourseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCourse);

        btnSearch.setBackground(new java.awt.Color(23, 65, 68));
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnEnroll.setBackground(new java.awt.Color(23, 65, 68));
        btnEnroll.setForeground(new java.awt.Color(255, 255, 255));
        btnEnroll.setText("ENROLL");
        btnEnroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollActionPerformed(evt);
            }
        });

        lblCourseID.setText("COURSE ID:");

        lblCourseName.setText("COURSE NAME:");

        lblCourseInstructor.setText("COURSE INSTRUCTOR:");

        lblCourseTimings.setText("COURSE TIMINGS:");

        txtCourseID.setEditable(false);

        txtCourseName.setEditable(false);
        txtCourseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseNameActionPerformed(evt);
            }
        });

        txtCourseInstructor.setEditable(false);
        txtCourseInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseInstructorActionPerformed(evt);
            }
        });

        txtCourseTimings.setEditable(false);

        lblReputativeIndex.setText("REPUTATIVE INDEX:");

        txtReputativeIndex.setEditable(false);
        txtReputativeIndex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReputativeIndexActionPerformed(evt);
            }
        });

        btnView.setBackground(new java.awt.Color(23, 65, 68));
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setText("VIEW");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        lblHeading.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblHeading.setText("PLEASE ENROLL TO THE COURSE");

        lblCredits.setText("CREDITS:");

        txtCredits.setEditable(false);
        txtCredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreditsActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(23, 65, 68));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCourseInstructor)
                                    .addComponent(lblCourseName)
                                    .addComponent(lblCourseID)
                                    .addComponent(lblCourseTimings)
                                    .addComponent(lblReputativeIndex)
                                    .addComponent(lblCredits))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCourseInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCourseTimings, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtReputativeIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEnroll, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(lblHeading))))
                    .addComponent(btnBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnView)
                .addGap(56, 56, 56)
                .addComponent(lblHeading)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseID)
                    .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseName)
                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseInstructor)
                    .addComponent(txtCourseInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseTimings)
                    .addComponent(txtCourseTimings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCredits)
                    .addComponent(txtCredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReputativeIndex)
                    .addComponent(txtReputativeIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(btnEnroll)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblCourseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblCourseFocusGained

//        setVisibility(true);
//        int selectedRowIndex = tblCourse.getSelectedRow();
//        
//        if(selectedRowIndex >=0){
//        Course course = (Course) tblCourse.getValueAt(selectedRowIndex, 0);
//        
//        course.setCourseId(txtCourseID.getText());
//        }
    }//GEN-LAST:event_tblCourseFocusGained

    private void tblCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCourseMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCourseMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        Course result = business.getCourseDirectory().searchCourse(txtSearch.getText());
        if(result == null){
            JOptionPane.showMessageDialog(this, "Course number you entered does not exist", "Information", JOptionPane.INFORMATION_MESSAGE);
        }else{

            DefaultTableModel model = (DefaultTableModel) tblCourse.getModel();
            model.setRowCount(0);

            Object[] row = new Object[4];
            row[0] = result;
            row[1] = result.getCourseName();
            row[2] = result.getCourseInstructor();
            row[3] = result.getCourseTimings();
            model.addRow(row);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollActionPerformed

         
        String courseID = txtCourseID.getText();
        StudentProfile studentProfile = business.getStudentDirectory().findStudent(studentID);
        System.out.println("STUDENT PROFILE: "+studentProfile);
        CourseDirectory courseDirectory = business.getCourseDirectory();
        Course course = courseDirectory.searchCourse(courseID);
        course.addNewStudent(studentProfile);
        
        if(studentProfile.getCourseWork().findCourseEnrolled(course) != null){
            JOptionPane.showMessageDialog(this, "You've already enrolled to this course!");
        }   
        else{
            CourseEnrolled courseEnrolled = new CourseEnrolled(course,"","");
            ArrayList<CourseEnrolled> courseWork = studentProfile.addNewCourseWork(courseEnrolled);

            JOptionPane.showMessageDialog(this, "Congragulations!, You've been enrolled to this course");
            UserActivity userActitvity = new UserActivity(studentProfile.getPerson().getFirstName(), "ONLINE", Activity.STUDENT_ENROLLED_TO_COURSE, new Date());
            business.getUserActivityDirectory().addUserActivity(userActitvity);
            setVisibility(false); 
        }
        
    }//GEN-LAST:event_btnEnrollActionPerformed

    private void txtCourseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseNameActionPerformed

    private void txtCourseInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseInstructorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseInstructorActionPerformed

    private void txtReputativeIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReputativeIndexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReputativeIndexActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        
        setVisibility(true);
        int selectedRowIndex = tblCourse.getSelectedRow();
        
        if(selectedRowIndex >=0){
        Course course = (Course) tblCourse.getValueAt(selectedRowIndex, 0);
        txtCourseID.setText(course.getCourseId());
        txtCourseName.setText(course.getCourseName());
        txtCourseInstructor.setText(course.getCourseInstructor());
        txtCourseTimings.setText(course.getCourseTimings());
        txtCredits.setText(String.valueOf(course.getCreditsCarried()));
        
        String pid = course.getProfessorId();
        ProfessorProfile professor = business.getProfessorDirectory().findProfessor(pid);
        txtReputativeIndex.setText(String.valueOf(professor.getReputativeIndex()));

        }
        else{
            JOptionPane.showMessageDialog(this, "Please select a row a view");
            return;
        }
        
        populateTable();

    }//GEN-LAST:event_btnViewActionPerformed

    private void txtCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreditsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreditsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEnroll;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCourseID;
    private javax.swing.JLabel lblCourseInstructor;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblCourseTimings;
    private javax.swing.JLabel lblCredits;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblReputativeIndex;
    private javax.swing.JTable tblCourse;
    private javax.swing.JTextField txtCourseID;
    private javax.swing.JTextField txtCourseInstructor;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtCourseTimings;
    private javax.swing.JTextField txtCredits;
    private javax.swing.JTextField txtReputativeIndex;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
