/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Business;
import model.Course;
import model.CourseEnrolled;
import model.StudentProfile;

/**
 *
 * @author saralask
 */
public class StudentCourseWorkJPanel extends javax.swing.JPanel {

    JPanel CardSequencePanel;
    Business business;
    String studentID;
    /**
     * Creates new form StudentCourseWorkJPanel
     */
    public StudentCourseWorkJPanel(Business bz, JPanel jp, String studentID) {
        initComponents();
        CardSequencePanel = jp;
        this.business = bz;
        this.studentID = studentID;
        populateTable();
    }
    
    private void populateTable(){
        
        ArrayList<CourseEnrolled> coursesEnrolled = business.getStudentDirectory().findStudent(studentID).getCourseWork().getCourseEnrolledList();
       
        DefaultTableModel model = (DefaultTableModel) tblCourseEnrolled.getModel();
        model.setRowCount(0);
        
        if(coursesEnrolled!=null){
            for(CourseEnrolled course : coursesEnrolled){
            Object[] row = new Object[4];
            row[0] = course;
            row[1] = course.getCourse().getCourseName();
            row[2] = course.getCourse().getCourseInstructor();
            row[3] = course.getGradeEarned();
            model.addRow(row);
        } 
        }
        
    }
    
     private void setVisibility(boolean flag){
        lblCourseID.setVisible(flag);
        txtCourseID.setVisible(flag);
        lblCourseName.setVisible(flag);
        txtCourseName.setVisible(flag);
        lblCourseInstructor.setVisible(flag);
        txtCourseInstructor.setVisible(flag);
        lblGrades.setVisible(flag);
        txtGrades.setVisible(flag);
        lblRemarks.setVisible(flag);
        txtAreaRemarks.setVisible(flag);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourseEnrolled = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        lblCourseID = new javax.swing.JLabel();
        txtCourseID = new javax.swing.JTextField();
        lblCourseName = new javax.swing.JLabel();
        txtCourseName = new javax.swing.JTextField();
        lblCourseInstructor = new javax.swing.JLabel();
        txtCourseInstructor = new javax.swing.JTextField();
        lblGrades = new javax.swing.JLabel();
        txtGrades = new javax.swing.JTextField();
        lblRemarks = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaRemarks = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(203, 231, 229));

        btnSearch.setBackground(new java.awt.Color(23, 65, 68));
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblCourseEnrolled.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Name", "Instructor ", "Grade Earned"
            }
        ));
        tblCourseEnrolled.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblCourseEnrolledFocusGained(evt);
            }
        });
        tblCourseEnrolled.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCourseEnrolledMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCourseEnrolled);

        btnView.setBackground(new java.awt.Color(23, 65, 68));
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setText("VIEW");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        lblCourseID.setText("COURSE ID:");

        txtCourseID.setEditable(false);

        lblCourseName.setText("COURSE NAME:");

        txtCourseName.setEditable(false);
        txtCourseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseNameActionPerformed(evt);
            }
        });

        lblCourseInstructor.setText("COURSE INSTRUCTOR:");

        txtCourseInstructor.setEditable(false);
        txtCourseInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseInstructorActionPerformed(evt);
            }
        });

        lblGrades.setText("GRADE EARNED:");

        txtGrades.setEditable(false);
        txtGrades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGradesActionPerformed(evt);
            }
        });

        lblRemarks.setText("REMARKS FROM PROFESSOR:");

        txtAreaRemarks.setEditable(false);
        txtAreaRemarks.setColumns(20);
        txtAreaRemarks.setRows(5);
        jScrollPane2.setViewportView(txtAreaRemarks);

        btnBack.setBackground(new java.awt.Color(23, 65, 68));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<<BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch)
                        .addContainerGap(679, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1033, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCourseInstructor)
                            .addComponent(lblCourseName)
                            .addComponent(lblCourseID)
                            .addComponent(lblGrades)
                            .addComponent(lblRemarks))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCourseInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGrades, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane2, txtCourseID, txtCourseInstructor, txtCourseName, txtGrades});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnView)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseID)
                    .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseName)
                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseInstructor)
                    .addComponent(txtCourseInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGrades)
                    .addComponent(txtGrades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblRemarks))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(44, 44, 44))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        String courseID = txtSearch.getText();
        Course course = business.getCourseDirectory().searchCourse(courseID);
        StudentProfile studentProfile = business.getStudentDirectory().findStudent(studentID);
        Course result = business.getCourseDirectory().searchCourse(txtSearch.getText());
        if(result == null){
            JOptionPane.showMessageDialog(this, "Course number you entered does not exist", "Information", JOptionPane.INFORMATION_MESSAGE);
        }else{

            DefaultTableModel model = (DefaultTableModel) tblCourseEnrolled.getModel();
            model.setRowCount(0);

            Object[] row = new Object[4];
            row[0] = result;
            row[1] = result.getCourseName();
            row[2] = result.getCourseInstructor();
            row[3] = studentProfile.getCourseWork().findCourseEnrolled(course).getGradeEarned();
            model.addRow(row);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tblCourseEnrolledFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblCourseEnrolledFocusGained

    }//GEN-LAST:event_tblCourseEnrolledFocusGained

    private void tblCourseEnrolledMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCourseEnrolledMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCourseEnrolledMouseClicked

    private void txtCourseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseNameActionPerformed

    private void txtCourseInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseInstructorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseInstructorActionPerformed

    private void txtGradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGradesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGradesActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed

        int selectedRowIndex = tblCourseEnrolled.getSelectedRow();
        
        if(selectedRowIndex >=0){
            CourseEnrolled courseEnrolled = (CourseEnrolled) tblCourseEnrolled.getValueAt(selectedRowIndex, 0);
            txtCourseID.setText(courseEnrolled.getCourse().getCourseId());
            txtCourseName.setText(courseEnrolled.getCourse().getCourseName());
            txtCourseInstructor.setText(courseEnrolled.getCourse().getCourseInstructor());
            txtGrades.setText(courseEnrolled.getGradeEarned());
            txtAreaRemarks.setText(courseEnrolled.getRemarks());
        }  else{
            JOptionPane.showMessageDialog(this,"Please select the row first");
        } 
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCourseID;
    private javax.swing.JLabel lblCourseInstructor;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblGrades;
    private javax.swing.JLabel lblRemarks;
    private javax.swing.JTable tblCourseEnrolled;
    private javax.swing.JTextArea txtAreaRemarks;
    private javax.swing.JTextField txtCourseID;
    private javax.swing.JTextField txtCourseInstructor;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtGrades;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
