/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * WorkAreaJPanel.java
 *
 * Created on May 17, 2020, 8:35:29 AM
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Business;
import model.StudentProfile;

/**
 *
 * @author kal
 */
public class StudentWorkAreaJPanel extends javax.swing.JPanel {

    javax.swing.JPanel CardSequencePanel;
    Business business;
    StudentProfile student;

    /**
     * Creates new form UnitRiskWorkArea
     * @param b
     * @param spp
     * @param clp
     */

    public StudentWorkAreaJPanel(Business b, StudentProfile spp, JPanel clp) {

        business = b;
        this.CardSequencePanel = clp;
        student = spp;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageProfile = new javax.swing.JButton();
        btnGraduationAudit = new javax.swing.JButton();
        btnRegistration = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        btnCourseWork = new javax.swing.JButton();

        setBackground(new java.awt.Color(203, 231, 229));
        setForeground(new java.awt.Color(51, 51, 51));

        btnManageProfile.setBackground(new java.awt.Color(23, 65, 68));
        btnManageProfile.setFont(getFont());
        btnManageProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnManageProfile.setText("MANAGE PROFILE");
        btnManageProfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageProfile.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageProfile.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageProfile.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProfileActionPerformed(evt);
            }
        });

        btnGraduationAudit.setBackground(new java.awt.Color(23, 65, 68));
        btnGraduationAudit.setFont(getFont());
        btnGraduationAudit.setForeground(new java.awt.Color(255, 255, 255));
        btnGraduationAudit.setText("GRADUATION AUDIT");
        btnGraduationAudit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGraduationAudit.setMaximumSize(new java.awt.Dimension(200, 40));
        btnGraduationAudit.setMinimumSize(new java.awt.Dimension(20, 20));
        btnGraduationAudit.setPreferredSize(new java.awt.Dimension(240, 25));
        btnGraduationAudit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraduationAuditActionPerformed(evt);
            }
        });

        btnRegistration.setBackground(new java.awt.Color(23, 65, 68));
        btnRegistration.setFont(getFont());
        btnRegistration.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistration.setText("REGISTRATION");
        btnRegistration.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistration.setMaximumSize(new java.awt.Dimension(200, 40));
        btnRegistration.setMinimumSize(new java.awt.Dimension(20, 20));
        btnRegistration.setPreferredSize(new java.awt.Dimension(240, 25));
        btnRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrationActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("My Student Portal");

        jButton12.setBackground(new java.awt.Color(23, 65, 68));
        jButton12.setFont(getFont());
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("TRANSCRIPT");
        jButton12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton12.setMaximumSize(new java.awt.Dimension(200, 40));
        jButton12.setMinimumSize(new java.awt.Dimension(20, 20));
        jButton12.setPreferredSize(new java.awt.Dimension(240, 25));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        btnCourseWork.setBackground(new java.awt.Color(23, 65, 68));
        btnCourseWork.setFont(getFont());
        btnCourseWork.setForeground(new java.awt.Color(255, 255, 255));
        btnCourseWork.setText("COURSE WORK");
        btnCourseWork.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCourseWork.setMaximumSize(new java.awt.Dimension(200, 40));
        btnCourseWork.setMinimumSize(new java.awt.Dimension(20, 23));
        btnCourseWork.setPreferredSize(new java.awt.Dimension(240, 30));
        btnCourseWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseWorkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(btnManageProfile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(btnCourseWork, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGraduationAudit, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(492, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCourseWork, btnGraduationAudit, btnManageProfile, btnRegistration, jButton12});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCourseWork, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGraduationAudit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(295, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProfileActionPerformed
        String studentID = student.getPerson().getId();
        StudentProfileJPanel studentCourseRegistration = new StudentProfileJPanel(business, CardSequencePanel,studentID);

        CardSequencePanel.add("Student Personal Profile", studentCourseRegistration);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
}//GEN-LAST:event_btnManageProfileActionPerformed

    private void btnGraduationAuditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraduationAuditActionPerformed
        String studentID = student.getPerson().getId();
        GraduationAuditJPanel graduationAuditJPanel = new GraduationAuditJPanel(business, CardSequencePanel,studentID);

        CardSequencePanel.add("Student Personal Profile", graduationAuditJPanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnGraduationAuditActionPerformed

    private void btnRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrationActionPerformed
        String studentID = student.getPerson().getId();
        StudentCourseRegistrationJPanel studentCourseRegistration = new StudentCourseRegistrationJPanel(business, CardSequencePanel,studentID);

        CardSequencePanel.add("Student Course Registration", studentCourseRegistration);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
}//GEN-LAST:event_btnRegistrationActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
         
        
        String studentID = student.getPerson().getId();
        if(business.getStudentDirectory().findStudent(studentID).getTotalGradesEarned()<8){
            JOptionPane.showMessageDialog(this, "Transcript is on hold");
        }
        else {
        StudentTranscriptJPanel studentCourseRegistration = new StudentTranscriptJPanel(business, CardSequencePanel,studentID);

        CardSequencePanel.add("Student Course Registration", studentCourseRegistration);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel); 
        }
           
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btnCourseWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseWorkActionPerformed
        String studentID = student.getPerson().getId();
        StudentCourseWorkJPanel studentCourseRegistration = new StudentCourseWorkJPanel(business, CardSequencePanel,studentID);

        CardSequencePanel.add("Student Course Registration", studentCourseRegistration);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnCourseWorkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCourseWork;
    private javax.swing.JButton btnGraduationAudit;
    private javax.swing.JButton btnManageProfile;
    private javax.swing.JButton btnRegistration;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
