/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import com.itextpdf.text.Image;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.FileOutputStream;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Business;
import model.CourseEnrolled;

/**
 *
 * @author saralask
 */
public class StudentTranscriptJPanel extends javax.swing.JPanel {

    JPanel CardSequencePanel;
    Business business;
    String studentID;
    /**
     * Creates new form StudentTranscript
     */
    public StudentTranscriptJPanel(Business bz, JPanel jp, String studentID) {
        initComponents();
        CardSequencePanel = jp;
        this.business = bz;
        this.studentID = studentID;
        populateTable();
    }
    
     private void populateTable(){ 
        ArrayList<CourseEnrolled> coursesEnrolled = business.getStudentDirectory().findStudent(String.valueOf(studentID)).getCourseWork().getCourseEnrolledList();

        System.out.println("COURSES ENROLLED: "+coursesEnrolled);
        DefaultTableModel model = (DefaultTableModel) tblCourseEnrolled.getModel();
        model.setRowCount(0);
        
        if(coursesEnrolled!=null){
            for(CourseEnrolled course : coursesEnrolled){
            
            Object[] row = new Object[4];
            row[0] = course;
            row[1] = course.getCourse().getCourseName();
            row[2] = course.getCourse().getCourseInstructor();
            row[3] = course.getGradeEarned(); 
            model.addRow(row);
        } 
        } 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourseEnrolled = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        btnDownload = new javax.swing.JButton();

        tblCourseEnrolled.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Name", "Instructor ", "Grade Earned"
            }
        ));
        tblCourseEnrolled.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblCourseEnrolledFocusGained(evt);
            }
        });
        tblCourseEnrolled.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCourseEnrolledMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCourseEnrolled);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("CONGRAGULATIONS ON YOUR GRADUATION");

        jLabel2.setText("HERE IS YOUR TRANSCRIPT");

        Back.setBackground(new java.awt.Color(23, 65, 68));
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        btnDownload.setBackground(new java.awt.Color(23, 65, 68));
        btnDownload.setForeground(new java.awt.Color(255, 255, 255));
        btnDownload.setText("DOWNLOAD");
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(460, 460, 460)
                .addComponent(btnDownload))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Back))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnDownload)
                .addGap(77, 77, 77)
                .addComponent(Back))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblCourseEnrolledFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblCourseEnrolledFocusGained

    }//GEN-LAST:event_tblCourseEnrolledFocusGained

    private void tblCourseEnrolledMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCourseEnrolledMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCourseEnrolledMouseClicked

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_BackActionPerformed

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        exportToPDF();
    }//GEN-LAST:event_btnDownloadActionPerformed


    private void exportToPDF() {
    try {
        // Convert JPanel to BufferedImage
        BufferedImage bi = new BufferedImage(1500, 1500, BufferedImage.TYPE_INT_RGB);
        Graphics2D g = bi.createGraphics();
        this.paint(g);
        g.dispose();

        // Create a new iText Document and add the BufferedImage to it
        com.itextpdf.text.Document document = new com.itextpdf.text.Document();
        PdfWriter.getInstance(document, new FileOutputStream("StudentTranscript.pdf"));
        document.open();

        Image image = Image.getInstance(bi, null);
        document.add(image);

        document.close();

        System.out.println("PDF Created!");
    } catch (Exception e) {
        e.printStackTrace();
    }
}




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton btnDownload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCourseEnrolled;
    // End of variables declaration//GEN-END:variables
}
